name: GitHub Classroom Workflow

on: [push]

permissions:
  checks: write
  actions: read
  contents: read

jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.MONGO_DB_URI }}
        run: |
          example-command "$MONGO_DB_URI"
      - uses: actions/checkout@v2
      - uses: education/autograding@v1
